// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-webapp/oauth.proto

package douyin_webapp // import "github.com/dev-openapi/douyin-webapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccessTokenReq struct {
	ClientSecret         string   `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	GrantType            string   `protobuf:"bytes,3,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	ClientKey            string   `protobuf:"bytes,4,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReq) Reset()         { *m = GetAccessTokenReq{} }
func (m *GetAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReq) ProtoMessage()    {}
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{0}
}
func (m *GetAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReq.Unmarshal(m, b)
}
func (m *GetAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReq.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReq.Merge(dst, src)
}
func (m *GetAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReq.Size(m)
}
func (m *GetAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReq proto.InternalMessageInfo

func (m *GetAccessTokenReq) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *GetAccessTokenReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetAccessTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *GetAccessTokenReq) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

type GetAccessTokenRes struct {
	Message              string                  `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Data                 *GetAccessTokenRes_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetAccessTokenRes) Reset()         { *m = GetAccessTokenRes{} }
func (m *GetAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes) ProtoMessage()    {}
func (*GetAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{1}
}
func (m *GetAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes.Unmarshal(m, b)
}
func (m *GetAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes.Merge(dst, src)
}
func (m *GetAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes.Size(m)
}
func (m *GetAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes proto.InternalMessageInfo

func (m *GetAccessTokenRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAccessTokenRes) GetData() *GetAccessTokenRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAccessTokenRes_Data struct {
	ErrorCode            int64    `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,2,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	OpenId               string   `protobuf:"bytes,3,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	RefreshExpiresIn     int64    `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn" json:"refresh_expires_in,omitempty"`
	RefreshToken         string   `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	Scope                string   `protobuf:"bytes,6,opt,name=scope" json:"scope,omitempty"`
	AccessToken          string   `protobuf:"bytes,7,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRes_Data) Reset()         { *m = GetAccessTokenRes_Data{} }
func (m *GetAccessTokenRes_Data) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes_Data) ProtoMessage()    {}
func (*GetAccessTokenRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{1, 0}
}
func (m *GetAccessTokenRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes_Data.Unmarshal(m, b)
}
func (m *GetAccessTokenRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes_Data.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes_Data.Merge(dst, src)
}
func (m *GetAccessTokenRes_Data) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes_Data.Size(m)
}
func (m *GetAccessTokenRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes_Data proto.InternalMessageInfo

func (m *GetAccessTokenRes_Data) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetAccessTokenRes_Data) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetAccessTokenRes_Data) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetRefreshExpiresIn() int64 {
	if m != nil {
		return m.RefreshExpiresIn
	}
	return 0
}

func (m *GetAccessTokenRes_Data) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RenewRefreshTokenReq struct {
	ClientKey            string   `protobuf:"bytes,1,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewRefreshTokenReq) Reset()         { *m = RenewRefreshTokenReq{} }
func (m *RenewRefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RenewRefreshTokenReq) ProtoMessage()    {}
func (*RenewRefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{2}
}
func (m *RenewRefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewRefreshTokenReq.Unmarshal(m, b)
}
func (m *RenewRefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewRefreshTokenReq.Marshal(b, m, deterministic)
}
func (dst *RenewRefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewRefreshTokenReq.Merge(dst, src)
}
func (m *RenewRefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RenewRefreshTokenReq.Size(m)
}
func (m *RenewRefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewRefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RenewRefreshTokenReq proto.InternalMessageInfo

func (m *RenewRefreshTokenReq) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *RenewRefreshTokenReq) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RenewRefreshTokenRes struct {
	Message              string                     `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Data                 *RenewRefreshTokenRes_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RenewRefreshTokenRes) Reset()         { *m = RenewRefreshTokenRes{} }
func (m *RenewRefreshTokenRes) String() string { return proto.CompactTextString(m) }
func (*RenewRefreshTokenRes) ProtoMessage()    {}
func (*RenewRefreshTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{3}
}
func (m *RenewRefreshTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewRefreshTokenRes.Unmarshal(m, b)
}
func (m *RenewRefreshTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewRefreshTokenRes.Marshal(b, m, deterministic)
}
func (dst *RenewRefreshTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewRefreshTokenRes.Merge(dst, src)
}
func (m *RenewRefreshTokenRes) XXX_Size() int {
	return xxx_messageInfo_RenewRefreshTokenRes.Size(m)
}
func (m *RenewRefreshTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewRefreshTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_RenewRefreshTokenRes proto.InternalMessageInfo

func (m *RenewRefreshTokenRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RenewRefreshTokenRes) GetData() *RenewRefreshTokenRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RenewRefreshTokenRes_Data struct {
	Description          string   `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,3,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewRefreshTokenRes_Data) Reset()         { *m = RenewRefreshTokenRes_Data{} }
func (m *RenewRefreshTokenRes_Data) String() string { return proto.CompactTextString(m) }
func (*RenewRefreshTokenRes_Data) ProtoMessage()    {}
func (*RenewRefreshTokenRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{3, 0}
}
func (m *RenewRefreshTokenRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewRefreshTokenRes_Data.Unmarshal(m, b)
}
func (m *RenewRefreshTokenRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewRefreshTokenRes_Data.Marshal(b, m, deterministic)
}
func (dst *RenewRefreshTokenRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewRefreshTokenRes_Data.Merge(dst, src)
}
func (m *RenewRefreshTokenRes_Data) XXX_Size() int {
	return xxx_messageInfo_RenewRefreshTokenRes_Data.Size(m)
}
func (m *RenewRefreshTokenRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewRefreshTokenRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RenewRefreshTokenRes_Data proto.InternalMessageInfo

func (m *RenewRefreshTokenRes_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RenewRefreshTokenRes_Data) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RenewRefreshTokenRes_Data) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *RenewRefreshTokenRes_Data) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type GetClientTokenReq struct {
	ClientKey            string   `protobuf:"bytes,1,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	GrantType            string   `protobuf:"bytes,3,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientTokenReq) Reset()         { *m = GetClientTokenReq{} }
func (m *GetClientTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetClientTokenReq) ProtoMessage()    {}
func (*GetClientTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{4}
}
func (m *GetClientTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientTokenReq.Unmarshal(m, b)
}
func (m *GetClientTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientTokenReq.Marshal(b, m, deterministic)
}
func (dst *GetClientTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientTokenReq.Merge(dst, src)
}
func (m *GetClientTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetClientTokenReq.Size(m)
}
func (m *GetClientTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientTokenReq proto.InternalMessageInfo

func (m *GetClientTokenReq) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *GetClientTokenReq) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *GetClientTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

type GetClientTokenRes struct {
	Message              string                  `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Data                 *GetClientTokenRes_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetClientTokenRes) Reset()         { *m = GetClientTokenRes{} }
func (m *GetClientTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetClientTokenRes) ProtoMessage()    {}
func (*GetClientTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{5}
}
func (m *GetClientTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientTokenRes.Unmarshal(m, b)
}
func (m *GetClientTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientTokenRes.Marshal(b, m, deterministic)
}
func (dst *GetClientTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientTokenRes.Merge(dst, src)
}
func (m *GetClientTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetClientTokenRes.Size(m)
}
func (m *GetClientTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientTokenRes proto.InternalMessageInfo

func (m *GetClientTokenRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetClientTokenRes) GetData() *GetClientTokenRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetClientTokenRes_Data struct {
	ExpiresIn            int64    `protobuf:"varint,1,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ErrorCode            int64    `protobuf:"varint,4,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientTokenRes_Data) Reset()         { *m = GetClientTokenRes_Data{} }
func (m *GetClientTokenRes_Data) String() string { return proto.CompactTextString(m) }
func (*GetClientTokenRes_Data) ProtoMessage()    {}
func (*GetClientTokenRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{5, 0}
}
func (m *GetClientTokenRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientTokenRes_Data.Unmarshal(m, b)
}
func (m *GetClientTokenRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientTokenRes_Data.Marshal(b, m, deterministic)
}
func (dst *GetClientTokenRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientTokenRes_Data.Merge(dst, src)
}
func (m *GetClientTokenRes_Data) XXX_Size() int {
	return xxx_messageInfo_GetClientTokenRes_Data.Size(m)
}
func (m *GetClientTokenRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientTokenRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientTokenRes_Data proto.InternalMessageInfo

func (m *GetClientTokenRes_Data) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetClientTokenRes_Data) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetClientTokenRes_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetClientTokenRes_Data) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type RefreshAccessTokenReq struct {
	ClientKey            string   `protobuf:"bytes,1,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	GrantType            string   `protobuf:"bytes,2,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenReq) Reset()         { *m = RefreshAccessTokenReq{} }
func (m *RefreshAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenReq) ProtoMessage()    {}
func (*RefreshAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{6}
}
func (m *RefreshAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenReq.Unmarshal(m, b)
}
func (m *RefreshAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenReq.Marshal(b, m, deterministic)
}
func (dst *RefreshAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenReq.Merge(dst, src)
}
func (m *RefreshAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenReq.Size(m)
}
func (m *RefreshAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenReq proto.InternalMessageInfo

func (m *RefreshAccessTokenReq) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *RefreshAccessTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *RefreshAccessTokenReq) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshAccessTokenRes struct {
	Message              string                      `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Data                 *RefreshAccessTokenRes_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RefreshAccessTokenRes) Reset()         { *m = RefreshAccessTokenRes{} }
func (m *RefreshAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenRes) ProtoMessage()    {}
func (*RefreshAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{7}
}
func (m *RefreshAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenRes.Unmarshal(m, b)
}
func (m *RefreshAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenRes.Marshal(b, m, deterministic)
}
func (dst *RefreshAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenRes.Merge(dst, src)
}
func (m *RefreshAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenRes.Size(m)
}
func (m *RefreshAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenRes proto.InternalMessageInfo

func (m *RefreshAccessTokenRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RefreshAccessTokenRes) GetData() *RefreshAccessTokenRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RefreshAccessTokenRes_Data struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope" json:"scope,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	ErrorCode            int32    `protobuf:"varint,5,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,6,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	OpenId               string   `protobuf:"bytes,7,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	RefreshExpiresIn     int64    `protobuf:"varint,8,opt,name=refresh_expires_in,json=refreshExpiresIn" json:"refresh_expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenRes_Data) Reset()         { *m = RefreshAccessTokenRes_Data{} }
func (m *RefreshAccessTokenRes_Data) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenRes_Data) ProtoMessage()    {}
func (*RefreshAccessTokenRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_oauth_b41df456aa64404b, []int{7, 0}
}
func (m *RefreshAccessTokenRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenRes_Data.Unmarshal(m, b)
}
func (m *RefreshAccessTokenRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenRes_Data.Marshal(b, m, deterministic)
}
func (dst *RefreshAccessTokenRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenRes_Data.Merge(dst, src)
}
func (m *RefreshAccessTokenRes_Data) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenRes_Data.Size(m)
}
func (m *RefreshAccessTokenRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenRes_Data proto.InternalMessageInfo

func (m *RefreshAccessTokenRes_Data) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshAccessTokenRes_Data) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *RefreshAccessTokenRes_Data) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshAccessTokenRes_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RefreshAccessTokenRes_Data) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RefreshAccessTokenRes_Data) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *RefreshAccessTokenRes_Data) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *RefreshAccessTokenRes_Data) GetRefreshExpiresIn() int64 {
	if m != nil {
		return m.RefreshExpiresIn
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAccessTokenReq)(nil), "open.douyin.com.GetAccessTokenReq")
	proto.RegisterType((*GetAccessTokenRes)(nil), "open.douyin.com.GetAccessTokenRes")
	proto.RegisterType((*GetAccessTokenRes_Data)(nil), "open.douyin.com.GetAccessTokenRes.Data")
	proto.RegisterType((*RenewRefreshTokenReq)(nil), "open.douyin.com.RenewRefreshTokenReq")
	proto.RegisterType((*RenewRefreshTokenRes)(nil), "open.douyin.com.RenewRefreshTokenRes")
	proto.RegisterType((*RenewRefreshTokenRes_Data)(nil), "open.douyin.com.RenewRefreshTokenRes.Data")
	proto.RegisterType((*GetClientTokenReq)(nil), "open.douyin.com.GetClientTokenReq")
	proto.RegisterType((*GetClientTokenRes)(nil), "open.douyin.com.GetClientTokenRes")
	proto.RegisterType((*GetClientTokenRes_Data)(nil), "open.douyin.com.GetClientTokenRes.Data")
	proto.RegisterType((*RefreshAccessTokenReq)(nil), "open.douyin.com.RefreshAccessTokenReq")
	proto.RegisterType((*RefreshAccessTokenRes)(nil), "open.douyin.com.RefreshAccessTokenRes")
	proto.RegisterType((*RefreshAccessTokenRes_Data)(nil), "open.douyin.com.RefreshAccessTokenRes.Data")
}

func init() { proto.RegisterFile("douyin-webapp/oauth.proto", fileDescriptor_oauth_b41df456aa64404b) }

var fileDescriptor_oauth_b41df456aa64404b = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x4f, 0xd4, 0x40,
	0x14, 0xcf, 0x74, 0xbb, 0xbb, 0x30, 0x80, 0xca, 0x88, 0xb1, 0x36, 0x4a, 0xb0, 0x20, 0x9a, 0x15,
	0x76, 0x13, 0xbc, 0x61, 0xa2, 0x51, 0x34, 0x86, 0x78, 0x30, 0x59, 0x38, 0x71, 0x69, 0x4a, 0xfb,
	0x58, 0x1a, 0xa0, 0xd3, 0x9d, 0x19, 0xfe, 0xac, 0x27, 0xe3, 0x4d, 0x8c, 0x27, 0x3f, 0x80, 0x1f,
	0xca, 0xaf, 0xe0, 0x67, 0x30, 0x9e, 0x8c, 0x99, 0x69, 0x81, 0xb6, 0x53, 0xdb, 0x35, 0xde, 0x3a,
	0xef, 0xbd, 0x79, 0x7f, 0x7e, 0xbf, 0xf7, 0xde, 0x14, 0xdf, 0x09, 0xe8, 0xf1, 0x28, 0x8c, 0x56,
	0x4f, 0x61, 0xd7, 0x8b, 0xe3, 0x1e, 0xf5, 0x8e, 0xc5, 0x7e, 0x37, 0x66, 0x54, 0x50, 0x72, 0x9d,
	0xc6, 0x10, 0x75, 0x13, 0x7d, 0xd7, 0xa7, 0x47, 0xf6, 0xdd, 0x01, 0xa5, 0x83, 0x43, 0xe8, 0x79,
	0x71, 0xd8, 0xf3, 0xa2, 0x88, 0x0a, 0x4f, 0x84, 0x34, 0xe2, 0x89, 0xb9, 0x73, 0x8e, 0xf0, 0xec,
	0x1b, 0x10, 0x2f, 0x7c, 0x1f, 0x38, 0xdf, 0xa6, 0x07, 0x10, 0xf5, 0x61, 0x48, 0x16, 0xf1, 0x8c,
	0x7f, 0x18, 0x42, 0x24, 0x5c, 0x0e, 0x3e, 0x03, 0x61, 0xa1, 0x05, 0xf4, 0x68, 0xb2, 0x3f, 0x9d,
	0x08, 0xb7, 0x94, 0x8c, 0x10, 0x6c, 0xfa, 0x34, 0x00, 0xcb, 0x50, 0x3a, 0xf5, 0x4d, 0xee, 0x61,
	0x3c, 0x60, 0x5e, 0x24, 0x5c, 0x31, 0x8a, 0xc1, 0x6a, 0x28, 0xcd, 0xa4, 0x92, 0x6c, 0x8f, 0x62,
	0xa5, 0x4e, 0xfd, 0x1e, 0xc0, 0xc8, 0x32, 0x13, 0x75, 0x22, 0x79, 0x0b, 0x23, 0xe7, 0x97, 0xa1,
	0x27, 0xc3, 0x89, 0x85, 0xdb, 0x47, 0xc0, 0xb9, 0x37, 0x80, 0x34, 0x8d, 0x8b, 0x23, 0x79, 0x8a,
	0xcd, 0xc0, 0x13, 0x9e, 0xca, 0x60, 0x6a, 0xed, 0x61, 0xb7, 0x50, 0x7a, 0x57, 0xf3, 0xd5, 0x7d,
	0xe5, 0x09, 0xaf, 0xaf, 0x2e, 0xd9, 0x9f, 0x0d, 0x6c, 0xca, 0xa3, 0x4c, 0x0a, 0x18, 0xa3, 0xcc,
	0x55, 0xd5, 0xc8, 0x10, 0x8d, 0xfe, 0xa4, 0x92, 0x6c, 0xa4, 0x25, 0xc1, 0x59, 0x1c, 0x32, 0xe0,
	0x6e, 0x18, 0xa9, 0x50, 0x52, 0x9d, 0x48, 0x36, 0x23, 0x72, 0x1b, 0xb7, 0x65, 0x58, 0x37, 0x0c,
	0xd2, 0x72, 0x5b, 0xf2, 0xb8, 0x19, 0x90, 0x15, 0x4c, 0x18, 0xec, 0x31, 0xe0, 0xfb, 0x6e, 0xe6,
	0xbe, 0xa9, 0xee, 0xdf, 0x48, 0x35, 0xaf, 0x2f, 0xdd, 0x2c, 0xe2, 0x99, 0x0b, 0x6b, 0x21, 0x93,
	0xb5, 0x9a, 0x09, 0xe2, 0xa9, 0x50, 0x15, 0x40, 0xe6, 0x70, 0x93, 0xfb, 0x34, 0x06, 0xab, 0xa5,
	0x94, 0xc9, 0x81, 0xdc, 0xc7, 0xd3, 0x9e, 0xaa, 0x32, 0xbd, 0xd9, 0x56, 0xca, 0x29, 0xef, 0xaa,
	0x72, 0xb2, 0x80, 0xa7, 0x02, 0xe0, 0x3e, 0x0b, 0x63, 0xc9, 0xbd, 0x35, 0x91, 0x58, 0x64, 0x44,
	0xce, 0x0e, 0x9e, 0xeb, 0x43, 0x04, 0xa7, 0xfd, 0x4c, 0x3c, 0xd9, 0x09, 0x79, 0xc6, 0x50, 0x81,
	0x31, 0x3d, 0x6d, 0x43, 0x4f, 0xdb, 0xf9, 0x8d, 0x4a, 0x9d, 0x57, 0x31, 0xfb, 0x2c, 0xc7, 0x6c,
	0x47, 0x63, 0xb6, 0xcc, 0x5d, 0x8e, 0x5c, 0x94, 0x92, 0x5b, 0xa8, 0x1c, 0x69, 0x95, 0x17, 0xe8,
	0x97, 0x01, 0x9b, 0x7f, 0xa7, 0xbf, 0x51, 0xa4, 0x5f, 0x03, 0xc0, 0x2c, 0x01, 0xe0, 0x44, 0xb5,
	0xf5, 0x86, 0x42, 0xed, 0x1f, 0x90, 0xcd, 0x8f, 0xa0, 0x51, 0x32, 0x82, 0xd5, 0xe3, 0xe6, 0xfc,
	0x44, 0x7a, 0xe0, 0xff, 0x9c, 0xa7, 0xbc, 0xaf, 0x2c, 0xe4, 0x9f, 0x50, 0x66, 0x9e, 0xae, 0x10,
	0x43, 0x45, 0xc4, 0x8a, 0xed, 0x6a, 0xd4, 0xb6, 0x6b, 0xa3, 0x8e, 0x34, 0xb3, 0x30, 0xb3, 0xce,
	0x7b, 0x7c, 0x2b, 0x6d, 0x8e, 0xc2, 0x62, 0xab, 0x01, 0x3d, 0x8f, 0xa7, 0x51, 0x5c, 0x5f, 0x1a,
	0xd9, 0x8d, 0x12, 0xb2, 0x3f, 0x34, 0xca, 0x83, 0x57, 0x01, 0xff, 0x3c, 0x07, 0xfc, 0xe3, 0x92,
	0x76, 0x2f, 0xf1, 0x57, 0xba, 0xcc, 0xb4, 0x14, 0x51, 0xd5, 0x1e, 0x31, 0xaa, 0xf6, 0x48, 0xa3,
	0x96, 0x18, 0xb3, 0x8e, 0x98, 0x66, 0xf5, 0x34, 0xb5, 0x2a, 0x96, 0x69, 0x7b, 0x8c, 0x65, 0x3a,
	0x51, 0xbe, 0x4c, 0xd7, 0xbe, 0x99, 0x78, 0xfa, 0x9d, 0x7c, 0x13, 0xb7, 0x80, 0x9d, 0x84, 0x3e,
	0x90, 0x33, 0x7c, 0x2d, 0xff, 0x16, 0x10, 0xa7, 0xf6, 0xb1, 0x18, 0xda, 0xf5, 0x36, 0xdc, 0x99,
	0xff, 0xf8, 0xfd, 0xc7, 0x57, 0xc3, 0x72, 0x6e, 0x26, 0x8f, 0x70, 0x2f, 0x8b, 0xe0, 0x3a, 0xea,
	0x90, 0x2f, 0x08, 0xcf, 0x6a, 0xcb, 0x8a, 0x3c, 0x18, 0x67, 0xa1, 0x0d, 0xed, 0xb1, 0xcc, 0xb8,
	0xd3, 0x51, 0x39, 0x2c, 0x39, 0x76, 0x9a, 0x03, 0x93, 0x46, 0x6e, 0xae, 0x0d, 0xd6, 0x5b, 0x9d,
	0x95, 0x3d, 0xca, 0x8e, 0x52, 0x24, 0x32, 0x53, 0x5c, 0x8e, 0x44, 0x7e, 0x57, 0xd9, 0xf5, 0x36,
	0x3a, 0x12, 0xe9, 0x9c, 0x5d, 0x22, 0x71, 0x8e, 0x30, 0xd1, 0xfb, 0x98, 0x2c, 0x8f, 0xd5, 0xec,
	0x43, 0x7b, 0x3c, 0x3b, 0xee, 0x2c, 0xa9, 0x34, 0xe6, 0x9d, 0xb9, 0x4b, 0x30, 0x4a, 0x60, 0x78,
	0xb9, 0xbc, 0xb3, 0x34, 0x08, 0xc5, 0xfe, 0xf1, 0xae, 0xf4, 0xd4, 0x0b, 0xe0, 0x64, 0x55, 0x7a,
	0x97, 0xbf, 0x48, 0xb9, 0x3f, 0xab, 0xdd, 0x96, 0xfa, 0x4b, 0x7a, 0xf2, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x70, 0x6e, 0xac, 0x2e, 0x71, 0x09, 0x00, 0x00,
}
