// Code generated by protoc-gen-go_api(github.com/dev-openapi/protoc-gen-go_api version=v1.0.0). DO NOT EDIT.
// source: douyin-webapp/permission.proto

package douyin_webapp

import (
	context "context"
	fmt "fmt"
	io "io"
	json "encoding/json"
	bytes "bytes"
	http "net/http"
	strings "strings"
)
// Reference imports to suppress errors if they are not otherwise used.
var _ = context.Background
var _ = http.NewRequest
var _ = io.Copy
var _ = bytes.Compare
var _ = json.Marshal
var _ = strings.Compare


// Client API for Permission service

type PermissionService interface {
	// GetAccessToken  获取 access_token form格式 https://developer.open-douyin.com/docs/resource/zh-CN/dop/develop/openapi/account-permission/get-access-token
	GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...Option) (*GetAccessTokenRes, error)
}

type permissionService struct {
	// opts
	opts *Options
}

func NewPermissionService(opts ...Option) PermissionService {
	opt := newOptions(opts...)
	if len(opt.addr) <= 0 {
		opt.addr = "https://open.douyin.com"
	}
	return &permissionService {
		opts: opt,
	}
}


func (c *permissionService) GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...Option) (*GetAccessTokenRes, error) {
	var res GetAccessTokenRes
	// options
	opt := buildOptions(c.opts, opts...)
	headers := make(map[string]string)
	// route
	rawURL := fmt.Sprintf("%s/oauth/access_token", opt.addr)

	// body
	var body io.Reader
	bodyForms := make(map[string]string)
	if in.GetClientKey() != "" {
		bodyForms["client_key"] = fmt.Sprintf("%v", in.GetClientKey())
	}
	if in.GetClientSecret() != "" {
		bodyForms["client_secret"] = fmt.Sprintf("%v", in.GetClientSecret())
	}
	if in.GetCode() != "" {
		bodyForms["code"] = fmt.Sprintf("%v", in.GetCode())
	}
	if in.GetGrantType() != "" {
		bodyForms["grant_type"] = fmt.Sprintf("%v", in.GetGrantType())
	}
	var bs []string
	for k, v := range bodyForms {
		bs = append(bs, fmt.Sprintf("%s=%s", k, v))
	}
	body = strings.NewReader(strings.Join(bs, "&"))
	headers["Content-Type"] = "application/x-www-form-urlencoded"

	req, err := http.NewRequest("POST", rawURL, body)
	if err != nil {
		return nil, err
	}
	
	// header
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := opt.DoRequest(opt.client, req)
	if err != nil {
		return nil, err
	}
	err = opt.DoResponse(resp, &res)
	return &res, err 

}
