// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-webapp/permission.proto

package douyin_webapp // import "github.com/dev-openapi/douyin-webapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccessTokenReq struct {
	ClientSecret         string   `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	GrantType            string   `protobuf:"bytes,3,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	ClientKey            string   `protobuf:"bytes,4,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReq) Reset()         { *m = GetAccessTokenReq{} }
func (m *GetAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReq) ProtoMessage()    {}
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_cf1a89ff5b55a974, []int{0}
}
func (m *GetAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReq.Unmarshal(m, b)
}
func (m *GetAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReq.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReq.Merge(dst, src)
}
func (m *GetAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReq.Size(m)
}
func (m *GetAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReq proto.InternalMessageInfo

func (m *GetAccessTokenReq) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *GetAccessTokenReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetAccessTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *GetAccessTokenReq) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

type GetAccessTokenRes struct {
	Message              string                  `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Data                 *GetAccessTokenRes_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetAccessTokenRes) Reset()         { *m = GetAccessTokenRes{} }
func (m *GetAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes) ProtoMessage()    {}
func (*GetAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_cf1a89ff5b55a974, []int{1}
}
func (m *GetAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes.Unmarshal(m, b)
}
func (m *GetAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes.Merge(dst, src)
}
func (m *GetAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes.Size(m)
}
func (m *GetAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes proto.InternalMessageInfo

func (m *GetAccessTokenRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAccessTokenRes) GetData() *GetAccessTokenRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAccessTokenRes_Data struct {
	ErrorCode            int64    `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,2,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	OpenId               string   `protobuf:"bytes,3,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	RefreshExpiresIn     int64    `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn" json:"refresh_expires_in,omitempty"`
	RefreshToken         string   `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	Scope                string   `protobuf:"bytes,6,opt,name=scope" json:"scope,omitempty"`
	AccessToken          string   `protobuf:"bytes,7,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRes_Data) Reset()         { *m = GetAccessTokenRes_Data{} }
func (m *GetAccessTokenRes_Data) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes_Data) ProtoMessage()    {}
func (*GetAccessTokenRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_cf1a89ff5b55a974, []int{1, 0}
}
func (m *GetAccessTokenRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes_Data.Unmarshal(m, b)
}
func (m *GetAccessTokenRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes_Data.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes_Data.Merge(dst, src)
}
func (m *GetAccessTokenRes_Data) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes_Data.Size(m)
}
func (m *GetAccessTokenRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes_Data proto.InternalMessageInfo

func (m *GetAccessTokenRes_Data) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetAccessTokenRes_Data) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetAccessTokenRes_Data) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetRefreshExpiresIn() int64 {
	if m != nil {
		return m.RefreshExpiresIn
	}
	return 0
}

func (m *GetAccessTokenRes_Data) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRes_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAccessTokenReq)(nil), "open.douyin.com.GetAccessTokenReq")
	proto.RegisterType((*GetAccessTokenRes)(nil), "open.douyin.com.GetAccessTokenRes")
	proto.RegisterType((*GetAccessTokenRes_Data)(nil), "open.douyin.com.GetAccessTokenRes.Data")
}

func init() {
	proto.RegisterFile("douyin-webapp/permission.proto", fileDescriptor_permission_cf1a89ff5b55a974)
}

var fileDescriptor_permission_cf1a89ff5b55a974 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x55, 0xd2, 0x6d, 0x42, 0x26, 0x2d, 0x50, 0x83, 0xc4, 0x2a, 0xa2, 0xa8, 0x6c, 0x10, 0x20,
	0xd4, 0xee, 0x4a, 0xe5, 0x06, 0x27, 0xbe, 0x84, 0x2a, 0x2e, 0x28, 0xed, 0x89, 0xcb, 0xca, 0xf1,
	0x4e, 0x37, 0x56, 0x1b, 0xdb, 0xb5, 0x9d, 0xc2, 0x1e, 0xb8, 0x70, 0x84, 0x1b, 0xfc, 0x34, 0xfe,
	0x02, 0x3f, 0x82, 0x23, 0xf2, 0x78, 0x5b, 0xd2, 0xf6, 0xd0, 0xdb, 0xce, 0x7b, 0xf3, 0xf1, 0xde,
	0xec, 0x18, 0x1e, 0x54, 0x7a, 0xd1, 0x48, 0xb5, 0xf3, 0x19, 0xa7, 0xdc, 0x98, 0xc2, 0xa0, 0x9d,
	0x4b, 0xe7, 0xa4, 0x56, 0xb9, 0xb1, 0xda, 0x6b, 0x76, 0x4b, 0x1b, 0x54, 0x79, 0x4c, 0xca, 0x85,
	0x9e, 0x8f, 0xee, 0xd7, 0x5a, 0xd7, 0xc7, 0x58, 0x70, 0x23, 0x0b, 0xae, 0x94, 0xf6, 0xdc, 0x4b,
	0xad, 0x5c, 0x4c, 0xcf, 0xbe, 0x77, 0x60, 0xe3, 0x3d, 0xfa, 0x57, 0x42, 0xa0, 0x73, 0x07, 0xfa,
	0x08, 0xd5, 0x04, 0x4f, 0xd8, 0x18, 0xd6, 0xc5, 0xb1, 0x44, 0xe5, 0x4b, 0x87, 0xc2, 0xa2, 0x4f,
	0x3b, 0x5b, 0x9d, 0xa7, 0x83, 0xc9, 0x5a, 0x04, 0xf7, 0x09, 0x63, 0x0c, 0x12, 0xa1, 0x2b, 0x4c,
	0xbb, 0xc4, 0xd1, 0x37, 0xdb, 0x04, 0xa8, 0x2d, 0x57, 0xbe, 0xf4, 0x8d, 0xc1, 0x74, 0x85, 0x98,
	0x01, 0x21, 0x07, 0x8d, 0x21, 0xba, 0xed, 0x7b, 0x84, 0x4d, 0x9a, 0x44, 0x3a, 0x22, 0x1f, 0xb0,
	0xc9, 0xfe, 0x76, 0xaf, 0x8a, 0x71, 0x2c, 0x85, 0xfe, 0x1c, 0x9d, 0xe3, 0x35, 0xb6, 0x32, 0xce,
	0x42, 0xf6, 0x12, 0x92, 0x8a, 0x7b, 0x4e, 0x0a, 0x86, 0xbb, 0x4f, 0xf2, 0x4b, 0xd6, 0xf3, 0x2b,
	0xbd, 0xf2, 0xb7, 0xdc, 0xf3, 0x09, 0x15, 0x8d, 0x7e, 0x74, 0x21, 0x09, 0x61, 0x10, 0x85, 0xd6,
	0x6a, 0x5b, 0x92, 0x9b, 0x30, 0x62, 0x65, 0x32, 0x20, 0xe4, 0x4d, 0x6b, 0x09, 0xbf, 0x18, 0x69,
	0xd1, 0x95, 0x52, 0xd1, 0xa8, 0x40, 0x47, 0x64, 0x4f, 0xb1, 0x7b, 0xd0, 0x0f, 0x63, 0x4b, 0x59,
	0xb5, 0x76, 0x7b, 0x21, 0xdc, 0xab, 0xd8, 0x36, 0x30, 0x8b, 0x87, 0x16, 0xdd, 0xac, 0x5c, 0xaa,
	0x4f, 0xa8, 0xfe, 0x76, 0xcb, 0xbc, 0x3b, 0x6f, 0x33, 0x86, 0xf5, 0xb3, 0x6c, 0x1f, 0xc4, 0xa6,
	0xab, 0x71, 0xe3, 0x2d, 0x48, 0x06, 0xd8, 0x5d, 0x58, 0x75, 0x42, 0x1b, 0x4c, 0x7b, 0x44, 0xc6,
	0x80, 0x3d, 0x84, 0x35, 0x4e, 0x2e, 0xdb, 0xca, 0x3e, 0x91, 0x43, 0xfe, 0xdf, 0x39, 0xdb, 0x82,
	0x61, 0x85, 0x4e, 0x58, 0x69, 0xc2, 0xbf, 0x4f, 0x6f, 0xc4, 0x8c, 0x25, 0x68, 0xf7, 0x67, 0x07,
	0x36, 0x3e, 0x9e, 0xdf, 0xd2, 0x3e, 0xda, 0x53, 0x29, 0x90, 0x7d, 0x85, 0x9b, 0x17, 0x77, 0xc8,
	0xb2, 0x6b, 0x97, 0x7c, 0x32, 0xba, 0x3e, 0xc7, 0x65, 0xe3, 0x6f, 0xbf, 0xff, 0xfc, 0xea, 0x6e,
	0x66, 0x77, 0x0a, 0xcd, 0x17, 0x7e, 0x56, 0x2c, 0x3b, 0x78, 0xd1, 0x7b, 0xb6, 0x7d, 0xa8, 0xed,
	0xfc, 0xf5, 0xe3, 0x4f, 0x8f, 0x6a, 0xe9, 0x67, 0x8b, 0x69, 0x68, 0x52, 0x54, 0x78, 0xba, 0x13,
	0x1a, 0x87, 0x43, 0xbe, 0xf0, 0x08, 0xa6, 0x3d, 0xba, 0xe5, 0xe7, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x58, 0x45, 0xcc, 0x2e, 0x1c, 0x03, 0x00, 0x00,
}
